tg

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,74 +25,74 @@ jobs:
       - name: Build and Test
         run: make lint-and-test
 
-  run-integration-tests:
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        python: ["3.10", "3.11"]
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - uses: actions/setup-python@v3
-        with:
-          python-version: "${{ matrix.python }}"
-      - name: Test Python version
-        run: |
-          installed="$(python --version)"
-          expected="${{ matrix.python }}"
-          echo $installed
-          [[ $installed =~ "Python ${expected}" ]] && echo "Configured Python" || (echo "Failed to configure Python" && exit 1)
-      - name: Start algod
-        run: make algod-start
-      - name: Install python dependencies
-        run: make setup-development
-      - name: Integration Tests Only
-        run: make test-integration
-      - name: Stop algod
-        run: make algod-stop
+  # run-integration-tests:
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     matrix:
+  #       python: ["3.10", "3.11"]
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: actions/setup-python@v3
+  #       with:
+  #         python-version: "${{ matrix.python }}"
+  #     - name: Test Python version
+  #       run: |
+  #         installed="$(python --version)"
+  #         expected="${{ matrix.python }}"
+  #         echo $installed
+  #         [[ $installed =~ "Python ${expected}" ]] && echo "Configured Python" || (echo "Failed to configure Python" && exit 1)
+  #     - name: Start algod
+  #       run: make algod-start
+  #     - name: Install python dependencies
+  #       run: make setup-development
+  #     - name: Integration Tests Only
+  #       run: make test-integration
+  #     - name: Stop algod
+  #       run: make algod-stop
 
-  build-docset:
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        python: [ "3.10" ]
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - uses: actions/setup-python@v3
-        with:
-          python-version: "${{ matrix.python }}"
-      - name: Install python dependencies
-        run: make setup-docs
-      - name: Make docs
-        run: make bundle-docs
-      - name: Archive docset
-        if: ${{ !env.ACT }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: pyteal.docset
-          path: docs/pyteal.docset.tar.gz
+  # build-docset:
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     matrix:
+  #       python: [ "3.10" ]
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: actions/setup-python@v3
+  #       with:
+  #         python-version: "${{ matrix.python }}"
+  #     - name: Install python dependencies
+  #       run: make setup-docs
+  #     - name: Make docs
+  #       run: make bundle-docs
+  #     - name: Archive docset
+  #       if: ${{ !env.ACT }}
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: pyteal.docset
+  #         path: docs/pyteal.docset.tar.gz
 
-  upload-to-pypi:
-    runs-on: ubuntu-20.04
-    container: python:3.10
-    needs: ['build-test', 'run-integration-tests', 'build-docset']
-    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Install dependencies
-        run: make setup-wheel
-      - name: Build package
-        run: make bdist-wheel
-      - name: Release
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          user: __token__
-          password: ${{ secrets.PYPI_API_TOKEN }}
+  # upload-to-pypi:
+  #   runs-on: ubuntu-20.04
+  #   container: python:3.10
+  #   needs: ['build-test', 'run-integration-tests', 'build-docset']
+  #   if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Install dependencies
+  #       run: make setup-wheel
+  #     - name: Build package
+  #       run: make bdist-wheel
+  #     - name: Release
+  #       uses: pypa/gh-action-pypi-publish@release/v1
+  #       with:
+  #         user: __token__
+  #         password: ${{ secrets.PYPI_API_TOKEN }}
