refactor tests and prepare for slow nightly

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -39,7 +39,49 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - name: Install python dependencies
-        run: make setup-development
-      - name: Build and Unit Tests
-        run: make lint-and-test
+      - name: Install Python dependencies, Build, and Test
+        run: make setup-build-test
+
+  integration-test:
+    needs: [check-date]
+    if: ${{ github.event_name == 'release' || needs.check_date.outputs.should_run == 'true' }}
+
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        python: ["3.10", "3.11"]
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-python@v3
+        with:
+          python-version: "${{ matrix.python }}"
+      - name: Test Python version
+        run: |
+          installed="$(python --version)"
+          expected="${{ matrix.python }}"
+          echo $installed
+          [[ $installed =~ "Python ${expected}" ]] && echo "Configured Python" || (echo "Failed to configure Python" && exit 1)
+      - name: Integration tests using algod
+        run: make algod-integration
+
+  nighly-slow:
+    needs: [check-date]
+    if: ${{ github.event_name == 'release' || needs.check_date.outputs.should_run == 'true' }}
+
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        python: ["3.10", "3.11"]
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-python@v3
+        with:
+          python-version: "${{ matrix.python }}"
+      - name: Insert slow tests here
+        run: make nighly-slow
